sudo: required

services:
  - docker

before_install:
  - docker build -t jimarchitelli/test-complex -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true jimarchitelli/test-complex npm test -- --coverage

after_success:
  - docker build -t jimarchitelli/prod-client ./client
  - docker build -t jimarchitelli/prod-nginx ./nginx
  - docker build -t jimarchitelli/prod-server ./server
  - docker build -t jimarchitelli/prod-worker ./worker

  #Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #Take images and pusah them to Docker Hub
  - docker push jimarchitelli/prod-client
  - docker push jimarchitelli/prod-nginx
  - docker push jimarchitelli/prod-server
  - docker push jimarchitelli/prod-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "milt-docker"
  env: "MiltDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-256162046807"
  bucket_path: "milt-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"