sudo: required

services:
  - docker

before_install:
  - docker build jmarchitelli/test-complex -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true jmarchitelli/test-complex npm test -- --coverage

after_success:
  - docker build jmarchitelli/prod-client ./client
  - docker build jmarchitelli/prod-nginx ./nginx
  - docker build jmarchitelli/prod-server ./server
  - docker build jmarchitelli/prod-worker ./worker

  #Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #Take images and pusah them to Docker Hub
  - docker push jmarchitelli/prod-nginx ./nginx
  - docker push jmarchitelli/prod-server ./server
  - docker push jmarchitelli/prod-worker ./worker